language: zh
pipeline:
- name: HFTransformersNLP
  model_name: bert
  model_weights: bert-base-chinese
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 10
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 10
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.3  # intent confidence threshold
  ambiguity_threshold: 0.1
  core_threshold: 0.3  # response action threshold
  fallback_action_name: action_response_command
