language: zh
pipeline:
- name: HFTransformersNLP
  model_name: bert
  model_weights: bert-base-chinese
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.5
  ambiguity_threshold: 0.2
  core_threshold: 0.3
  fallback_action_name: utter_fallback
